# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
    ]
