# Generated by Django 2.1.5 on 2019-02-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190131_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Please add only .PNG files for logo images. This logo will be used on certificates.', max_length=255, null=True, upload_to='organization_logos'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(db_index=True, help_text='Please do not use spaces or special characters. Only allowed special characters are period (.), hyphen (-) and underscore (_).', max_length=255, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='schoollogo',
            field=models.ImageField(blank=True, default='school_logo/no-image.jpg', upload_to='school_logo'),
        ),
        migrations.AlterField(
            model_name='userminiprofile',
            name='is_staff',
            field=models.BooleanField(blank=True),
        ),
    ]
