# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190226_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_page', models.CharField(max_length=10)),
                ('from_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_follow', to='api.Page')),
                ('to_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_follow', to='api.Page')),
            ],
        ),
    ]
