# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 15:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190226_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersectionmapping',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section', to=settings.AUTH_USER_MODEL),
        ),
    ]
