# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190226_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(db_index=True, help_text='Please do not use spaces or special characters. Only allowed special characters are period (.), hyphen (-) and underscore (_).', max_length=255, primary_key=True, serialize=False, verbose_name='Short Name'),
        ),
    ]
