# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190306_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='type_of_page',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userminiprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mini_user_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
