# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-31 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190315_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
