# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-05 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_school_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroup',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='school',
        ),
        migrations.AddField(
            model_name='globalgroup',
            name='group_image',
            field=models.ImageField(blank=True, default=b'school_logo/no-image.jpg', upload_to=b'school_logo'),
        ),
        migrations.AddField(
            model_name='globalgroup',
            name='longname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='globalgroup',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='globalgroup',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CourseGroup',
        ),
    ]
